import { useEffect, useMemo, useState, type ReactNode } from "react";

type TabKey = "assessment" | "content" | "digital" | "safety";
const tabs: { id: TabKey; label: string; icon: string }[] = [
  { id: "assessment", label: "Оценивание", icon: "📊" }, { id: "content", label: "Содержание", icon: "📖" },
  { id: "digital", label: "Цифра и ИИ", icon: "💻" }, { id: "safety", label: "Безопасность", icon: "🛡️" },
];
const palette = [{ name: "Небесный", color: "#8ec5ff" }, { name: "Мятный", color: "#86dfc7" }, { name: "Солнечный", color: "#ffd45a" }, { name: "Коралловый", color: "#ff8f87" }, { name: "Чернильный", color: "#273659" }];
const safetyRules = ["Не разговариваю с незнакомцами в сети и не принимаю подозрительные предложения", "Не сообщаю личные данные: адрес, пароли, данные родителей и школу", "Рассказываю взрослым о любых неприятных ситуациях в интернете", "Договариваюсь с семьёй о времени, которое провожу за экраном", "Проверяю информацию, прежде чем ей доверять или пересылать друзьям"];
const values = [["🤝", "Ответственность"], ["🇰🇿", "Патриотизм"], ["⚖️", "Уважение к закону"], ["💪", "Трудолюбие"], ["🌍", "Общечеловеческие ценности"], ["💚", "Доброжелательность"]];
const markMessages: Record<number, string> = { 1: "Начало положено! Давай разберёмся вместе.", 2: "Ты пробуешь — это уже шаг вперёд.", 3: "Найди ещё один способ решить задачу.", 4: "Хороший вопрос. Попробуй объяснить свой ход.", 5: "Половина пути! Ошибки помогают учиться.", 6: "Вижу прогресс — осталось немного практики.", 7: "Отличный результат! Что помогло тебе справиться?", 8: "Очень хорошо. Попробуй применить знание по-новому.", 9: "Почти мастерство! Поделись способом с классом.", 10: "Блестяще! Ты готов к следующему вызову." };

export default function Home() {
  const [selectedColors, setSelectedColors] = useState<string[]>([]); const [activeTab, setActiveTab] = useState<TabKey>("assessment"); const [mark, setMark] = useState(7); const [checked, setChecked] = useState<boolean[]>(Array(5).fill(false)); const [quizAnswer, setQuizAnswer] = useState<number | null>(null);
  useEffect(() => { const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && entry.target.classList.add("visible")), { threshold: 0.12 }); document.querySelectorAll(".reveal").forEach((el) => observer.observe(el)); return () => observer.disconnect(); }, []);
  const completed = checked.filter(Boolean).length; const paletteMessage = selectedColors.length === 3 ? "Гармонично! Три спокойных цвета — отличный выбор." : selectedColors.length > 3 ? "Можно выбрать только три цвета — убери один." : `${selectedColors.length} из 3 цветов выбрано`;
  const calendar = useMemo(() => [["I четверть", "8 недель", "1 сентября 2026", "26 октября — 1 ноября 2026"], ["II четверть", "8 недель", "2 ноября 2026", "7–13 декабря 2026"], ["III четверть", "10 недель", "14 декабря 2026", "18–31 марта 2027"], ["IV четверть", "8 недель", "1 апреля 2027", "25 мая 2027 — конец года"]], []);
  return <div className="portal-shell">
    <header className="topbar"><nav className="nav-wrap" aria-label="Основная навигация"><a href="#top" className="brand"><span className="brand-mark">⌂</span><span>Школа<span className="brand-accent">·портал</span></span></a><div className="nav-links"><a href="#uniform">Форма</a><a href="#changes">Изменения</a><a href="#marks">Оценивание</a><a href="#calendar">Календарь</a></div><a href="#kids" className="kids-link">🎈 Детская зона</a></nav></header>
    <main>
      <section id="top" className="hero section-pad"><div className="blob blob-yellow" /><div className="blob blob-teal" /><div className="blob blob-coral" /><div className="hero-content"><p className="eyebrow-pill">2026–2027 учебный год · Начальная школа РК</p><h1>Школа и семья —<br /><span>одна команда</span> <span className="hand-icon">🤝</span></h1><p className="hero-copy">Всё важное о новом учебном годе: форма, оценивание, календарь каникул и безопасность — простым языком для родителей и увлекательно для детей.</p><div className="hero-actions"><a href="#changes" className="button button-dark">👨‍👩‍👧 Родителям</a><a href="#kids" className="button button-sun">🎮 Детям — поиграть!</a></div></div><div className="marquee-wrap"><div className="marquee">📚 знания <b>✦</b> 🎨 творчество <b>✦</b> 🏃 здоровье <b>✦</b> 🤝 дружба <b>✦</b> 🛡️ безопасность <b>✦</b> 💻 цифровая грамотность <b>✦</b> 🌟 успехи <b>✦</b> &nbsp; 📚 знания <b>✦</b> 🎨 творчество <b>✦</b></div></div></section>
      <section id="uniform" className="content-section reveal"><SectionHeading n="1" title="Школьная форма" text="Классический стиль, спокойные цвета, безопасность. Производителя и место покупки родители выбирают сами!" /><div className="card-grid three"><InfoCard icon="🎽" title="Повседневная" text="Удобная одежда для каждого учебного дня. Светский стиль, требования школы и её устава." /><InfoCard icon="🤵" title="Парадная" text="Для торжественных линеек и мероприятий. Аккуратный, торжественный вид." /><InfoCard icon="🏀" title="Спортивная" text="Для уроков физкультуры: свобода движений и безопасность ребёнка." /></div><div className="interactive-card palette-card"><div><span className="mini-kicker">ИГРА ДЛЯ ВСЕХ</span><h3>🎨 Собери свой образ</h3><p>Правило: не более <b>трёх</b> спокойных, неярких цветов.</p></div><div className="palette-row">{palette.map((item) => <button aria-label={item.name} key={item.name} className={`color-chip ${selectedColors.includes(item.name) ? "selected" : ""}`} style={{ background: item.color }} onClick={() => setSelectedColors((current) => current.includes(item.name) ? current.filter((x) => x !== item.name) : [...current, item.name])}><span>{selectedColors.includes(item.name) ? "✓" : ""}</span></button>)}</div><p className={`palette-message ${selectedColors.length > 3 ? "error" : ""}`}>{paletteMessage}</p></div></section>
      <section id="changes" className="content-section reveal"><SectionHeading n="2" title="Главные изменения года" text="Четыре направления — выберите вкладку." /><div className="tabs">{tabs.map((tab) => <button key={tab.id} className={`tab ${activeTab === tab.id ? "active" : ""}`} onClick={() => setActiveTab(tab.id)}>{tab.icon} {tab.label}</button>)}</div><div className="tab-panel">{activeTab === "assessment" && <TwoCol><TextBlock accent="blue" title="2–4 классы" text="С 1 сентября 2026 года внедряются обновлённые подходы к оцениванию. Сохраняется критериальное оценивание, усиливается формативное." /><TextBlock accent="blue" title="Промежуточное оценивание" text="Вводится для определения результатов освоения учебных разделов — чтобы вовремя заметить трудности." /><TextBlock accent="blue" title="Главная цель" text="Больше обратной связи, своевременная поддержка и наблюдение за прогрессом ребёнка." /><Callout title="1 класс" text="Оценки по-прежнему не выставляются — главное это адаптация и учебные навыки." /></TwoCol>}{activeTab === "content" && <TwoCol><TextBlock accent="teal" title="Больше внимания базовым навыкам" text="У первоклассников — адаптационный период. Больше времени на «Әліппе» и «Ана тілі»: больше чтения и письма." /><TextBlock accent="teal" title="Оптимизация нагрузки" text="Пересматриваются отдельные цели по математике. Сохраняется курс на функциональную грамотность." /></TwoCol>}{activeTab === "digital" && <TwoCol><TextBlock accent="blue" title="Что развивается" text="Цифровая грамотность, современные образовательные ресурсы и знакомство с основами искусственного интеллекта — с учётом возраста ребёнка." /><Callout title="💡 Важно помнить" text="Цифровые технологии — инструмент обучения, а не замена живому общению." /></TwoCol>}{activeTab === "safety" && <TwoCol><TextBlock accent="coral" title="Комфорт ребёнка" text="Доброжелательная и безопасная атмосфера, профилактика буллинга, поддержка психологического благополучия." /><TextBlock accent="coral" title="Индивидуальный подход" text="Учёт индивидуальных образовательных потребностей каждого ребёнка остаётся важнейшим направлением." /></TwoCol>}</div></section>
      <section id="marks" className="content-section reveal"><SectionHeading n="3" title="Оценивание без стресса" text="Формативное оценивание — это не «отметка в журнал», а подсказка, что уже получается и над чем поработать." /><div className="assessment-grid"><div className="interactive-card slider-card"><span className="mini-kicker">ИНТЕРАКТИВ</span><h3>🎯 Подвигай ползунок — посмотри, что скажет учитель</h3><p>Шкала формативного оценивания: от 1 до 10 баллов</p><div className="mark-number">{mark}<small>/10</small></div><input type="range" min="1" max="10" value={mark} onChange={(e) => setMark(Number(e.target.value))} /><div className="feedback">{markMessages[mark]}</div></div><div className="card info-list"><h3>📋 Виды оценивания</h3><ListItem icon="🌱" title="Формативное" text="ежедневная обратная связь, шкала 1–10 баллов." /><ListItem icon="🧭" title="Промежуточное" text="результаты освоения учебных разделов." /><ListItem icon="🎈" title="1 класс" text="оценок нет, только адаптация и навыки." /><div className="dark-note">💛 Родителям: спрашивайте не «какая оценка?», а «что нового узнал и что интересного было?»</div></div></div></section>
      <section id="digital" className="content-section reveal"><SectionHeading n="4" title="Безопасность в интернете" text="Интерактивная памятка для всей семьи. Отмечайте правила, которые уже знаете!" /><div className="interactive-card checklist-card"><div className="check-head"><div><span className="mini-kicker">СЕМЕЙНЫЙ ЧЕК-ЛИСТ</span><h3>✅ Мой цифровой свод правил</h3></div><span className="count-badge">{checked.filter(Boolean).length} / 5</span></div><div className="progress"><span style={{ width: `${checked.filter(Boolean).length * 20}%` }} /></div><div className="rules">{safetyRules.map((rule, index) => <button key={rule} className={`rule ${checked[index] ? "done" : ""}`} onClick={() => setChecked((current) => current.map((value, i) => i === index ? !value : value))}><span className="check-box">{checked[index] ? "✓" : ""}</span><span>{rule}</span></button>)}</div><p className="check-message">{completed === 5 ? "Супер! Ты знаешь все правила цифровой безопасности." : completed ? "Продолжай — ещё немного!" : "Отмечай правила, которые уже знаешь"}</p></div></section>
      <section id="kids" className="content-section reveal"><SectionHeading n="5" title="Воспитание и ценности" text="Программа «Адал азамат» — в центре внимания личность ребёнка." /><div className="values-grid">{values.map(([icon, label]) => <div className="value-card" key={label}><span>{icon}</span><b>{label}</b></div>)}</div></section>
      <section id="team" className="content-section reveal"><SectionHeading n="6" title="Сотрудничество семьи и школы" /><div className="partner-grid"><Partner title="🏫 Школа" accent="blue" items={["Создаёт безопасную и развивающую среду", "Даёт своевременную обратную связь о прогрессе", "Поддерживает открытый диалог с родителями"]} /><Partner title="👨‍👩‍👧 Семья" accent="teal" items={["Поддерживает интерес ребёнка к обучению", "Помогает соблюдать режим дня и самостоятельность", "Сохраняет уважительный диалог с педагогами"]} /></div><div className="goal-banner"><span>🎯</span><div><h3>Наша общая цель</h3><p>Не только высокие результаты, но и здоровье, безопасность, уверенность и гармоничное развитие каждого ребёнка.</p></div></div></section>
      <section id="calendar" className="content-section reveal"><SectionHeading n="7" title="Календарь учебного года" text="1 сентября 2026 — 25 мая 2027" /><div className="calendar-layout"><div className="timeline card">{calendar.map(([quarter, weeks, start, holiday], index) => <div className="timeline-item" key={quarter}><span className={`timeline-dot ${index === 3 ? "teal" : ""}`} /><div><b>{quarter} · {weeks}</b><small>Начало: {start}</small><em>{index === 3 ? "🌟 " : "🌞 Каникулы: "}{holiday}</em></div></div>)}</div><div className="card calendar-side"><span className="calendar-icon">🗓️</span><h3>Планируйте заранее</h3><p>Сохраните даты каникул и важных школьных событий, чтобы учебный год был спокойнее.</p><button onClick={() => alert("Календарь готов к сохранению — добавьте эти даты в свой планировщик.")}>Добавить в планировщик →</button></div></div></section>
      <section className="quiz-section reveal"><div className="quiz-copy"><span className="mini-kicker">МИНИ-ВИКТОРИНА</span><h2>Проверим, всё ли запомнилось?</h2><p>Один вопрос для всей семьи. Обсудите ответ вместе.</p></div><div className="quiz-card"><div className="quiz-top"><span>Вопрос 1 из 1</span><span className="quiz-score">{quizAnswer === 1 ? "1 / 1" : "0 / 1"}</span></div><div className="quiz-bar"><span style={{ width: quizAnswer === null ? "35%" : "100%" }} /></div><h3>Что важнее всего в формативном оценивании?</h3>{["Сравнивать себя с одноклассниками", "Получать обратную связь и видеть свой прогресс", "Собирать как можно больше отметок"].map((answer, index) => <button key={answer} className={`quiz-option ${quizAnswer !== null && index === 1 ? "correct" : ""} ${quizAnswer === index && index !== 1 ? "wrong" : ""}`} onClick={() => setQuizAnswer(index)}>{answer}{quizAnswer !== null && index === 1 && <span>✓</span>}</button>)}{quizAnswer !== null && <p className="quiz-result">{quizAnswer === 1 ? "Верно! Учёба — это путь, а не соревнование." : "Попробуй ещё раз: ищи ответ про поддержку и прогресс."}</p>}</div></section>
    </main><footer><div className="footer-brand"><span className="brand-mark">⌂</span><b>Школа·портал</b></div><p>Вместе создаём спокойное, безопасное и интересное обучение.</p><small>2026–2027 · Для родителей и детей</small></footer>
  </div>;
}
function SectionHeading({ n, title, text }: { n: string; title: string; text?: string }) { return <div className="section-heading"><span className="section-number">{n}</span><div><h2>{title}</h2>{text && <p>{text}</p>}</div></div>; }
function InfoCard({ icon, title, text }: { icon: string; title: string; text: string }) { return <div className="card info-card"><span>{icon}</span><h3>{title}</h3><p>{text}</p></div>; }
function TwoCol({ children }: { children: ReactNode }) { return <div className="two-col">{children}</div>; }
function TextBlock({ title, text, accent }: { title: string; text: string; accent: string }) { return <div><h3 className={`accent-${accent}`}>{title}</h3><p>{text}</p></div>; }
function Callout({ title, text }: { title: string; text: string }) { return <div className="callout"><h3>{title}</h3><p>{text}</p></div>; }
function ListItem({ icon, title, text }: { icon: string; title: string; text: string }) { return <div className="list-item"><span>{icon}</span><p><b>{title}</b> — {text}</p></div>; }
function Partner({ title, accent, items }: { title: string; accent: string; items: string[] }) { return <div className={`partner-card ${accent}`}><h3>{title}</h3>{items.map((item) => <p key={item}>✔ <span>{item}</span></p>)}</div>; }
